name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Build and run services with Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d --build
          sleep 15  # give services time to start

      - name: Install test dependencies
        run: pip install requests

      - name: Run tests
        run: python3 -m pytest tests/

      - name: Shutdown containers
        if: always()
        run: docker compose down
